### ISSUE TITLE
GitHub action

### ISSUE THREAD

**Issue by marcanpilami** [marcanpilami/MAGE#20]
Once we have a proper Linux Dockerfile (#19) we need to hook it to GitHub action.

We need a pipeline
* which is run on every push or tag to master, also on every PR, which run all tests (django tests) and fails if tests are KO.
* if successful, only on master, on each push creates the Docker image with tag `nightly` and pushes it to the docker hub `enioka/mage` (secret to push to Docker hub is already available: `DOCKER_USERNAME`/`DOCKER_PASSWORD`)
* if successful, only on master AND associated to a tag, upload the same image to Docker Hub with the same tag.

If easier, can be cut into multiple pipelines.

**Comment by abessette** [comment]
From what has been done from now:

* Run django test on every push (tag and commit) to master (push includes PR, MR... Anything that can be associated to a commit)
* If successful create a docker image with the `nightly` tag and push it to docker hub `enioka/mage` 
* if successful and the event is a release, upload the docker image and push it to docker hub `enioka/mage` with the associated tag

Currently the `release` event on github IHM is not triggered on "draft save", only on "pre-release" tick checkbox with `publish` button click or just `publish` button click.

Another solution would be to simply publish the docker image on docker hub with the tag when the master branch is tagged...
